### ISSUE TITLE
Velero failes after restart

### ISSUE THREAD

**Issue by tormig** [konveyor/oadp-operator#73]
After an Openshift upgrade (4.6.4 to 4.6.6) Velero restarted and failed (CrashLoopBackOff). In the log the last entries are:

time="2020-12-03T13:58:41Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: Backup store contains invalid top-level directories: [docker]

This directory has been there since november 22 (it is an Minio docker instance) so why it suddenly is a  problem is unclear. After that directory was removed Velero works again.

**Comment by dymurray** [comment]
@tormig Thanks for the info, would you mind pasting a few files for me?

The `Velero` CR defiinition:
```
oc get velero -n oadp-operator -o yaml
```

The Velero deployment:
```
oc get deployment velero -n oadp-operator -o yaml
```

And the BSL:

```
oc get backupstoragelocations -n oadp-operator
```

That would be a huge help. The error is basically because Velero's BackupStorageLocation (the resource which connects Velero to the bucket) comes with a `prefix` setting where you can configure a directory for it to store data if it shares bucket with something else.

See https://github.com/konveyor/oadp-operator/blob/master/docs/bsl_and_vsl.md#configure-backup-storage-locations-and-volume-snapshot-locations for the place to put `prefix` in the `Velero` CR and perhaps this could resolve it. But if you send me the other info I can determine if thats the problem or not.

Thanks!

**Comment by tormig** [comment]
Hello

I can confirm straight away that there is no prefix. Since I did not expect to share this bucket with anything else I did not bother. Now it seems that Minio has added this "docker" bucket at some point. So I will add that prefix now to avoid this problem. 

Thanks for the update!

**Comment by dymurray** [comment]
Great! Assuming that resolves your issue I will close this out. Let me know if you run into any other trouble.
